---
title: 'Relatório: 2ª Rodada Laboratório 1'
author: "Joaquim e Isabelle"
date: "07-11-2023"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, message = FALSE)
```

```{r, include=FALSE}

#Pacotes utilizados

# install.packages("readxl")
# install.packages("tidyverse")
# install.packages("ggridges")
# install.packages("scales")
# install.packages("gmodels")
# install.packages("ggplot2")
# install.packages("caret")
# install.packages("leaps")
# install.packages("MASS")
# install.packages("dplyr")
# install.packages("reshape2")
# install.packages("ggridges")
# install.packages("kableExtra")
# install.packages("formattable")


library(ggplot2)
library(caret)
library(leaps)
library(MASS)
library(dplyr)
library(readxl)
library(tidyverse)
library(reshape2)
library(ggridges)
library(scales)
library(gmodels)
library(tidyr)
library(knitr)
library(magrittr)
library(kableExtra)
library(formattable)
```
\newpage

# 1. Introdução

<div style="text-align: justify">

<div/>

## 1.1 Objetivos Gerais do estudo

<div style="text-align: justify">

<div/>

## 1.2 Objetivos Específicos

<div style="text-align: justify">

<div/>
\newpage

# 2 Metodologia

<div style="text-align: justify">

<div/>
\newpage

# 3 Resultados

<div style="text-align: justify">

<div/>

## 3.1 Análise exploratória - Estatísticas descritivas

```{r, echo = FALSE, include = FALSE}

#Leitura e organizacao dos dados

banco <- read_excel("PESQUISA - Experiências de turistas motivados por produções audiovisuais (respostas).xlsx",
                    sheet = "Respostas ao formulário 1")
banco <- as.data.frame(banco)

names(banco)
```

```{r}
banco %>% 
  group_by(`12. A experiência turística e/ou cinematográfica vivida neste destino foi:`, 
           `1. Qual foi o sexo atribuído no seu nascimento?`) %>% 
  summarise(Quantidade=n()) %>% 
  group_by(`1. Qual foi o sexo atribuído no seu nascimento?`) %>% 
  mutate(Percentual = percent(Quantidade/sum(Quantidade),1)) %>% 
  ggplot(aes(x=`1. Qual foi o sexo atribuído no seu nascimento?`, y=Quantidade, 
           fill=`12. A experiência turística e/ou cinematográfica vivida neste destino foi:`,
           label = Percentual)) + 
  geom_bar(stat = "identity",position = "dodge") +
  scale_fill_manual(name="Tipo turista", values=c('#9cd1f0','#368196',"#69b3a2")) +
  geom_label(position = position_dodge(width = 1), show.legend = F, ) +
  labs(title = "Gráfico xx - Sexo versus Tipo de turista") +
  theme(plot.title=element_text(hjust = 0.5, size=11, face = "bold")) + 
  theme(axis.title.y = element_blank()) + 
  theme(axis.title.x = element_blank()) +
  theme(legend.title = element_text(size = 10))

```

```{r}
banco %>% 
  group_by(`8. Com que frequência você assiste a filmes, séries, telenovelas, clipes musicais ou outras produções audiovisuais?`, `12. A experiência turística e/ou cinematográfica vivida neste destino foi:`) %>% 
  summarise(Quantidade=n()) %>% 
  group_by(`8. Com que frequência você assiste a filmes, séries, telenovelas, clipes musicais ou outras produções audiovisuais?`) %>%
  mutate(Percentual = percent(Quantidade/sum(Quantidade),0)) %>% 
  ggplot(aes(x=`8. Com que frequência você assiste a filmes, séries, telenovelas, clipes musicais ou outras produções audiovisuais?`, y=Quantidade, 
           fill=`12. A experiência turística e/ou cinematográfica vivida neste destino foi:`, label = Percentual)) + 
  geom_bar(stat = "identity",position = "dodge") +
  scale_fill_manual(name="Tipo turista", values=c('#9cd1f0','#368196',"#60b3a2","#9cc1f0","#80b1b2")) +
  geom_label(position = position_dodge(width = 1), show.legend = F, size=3) +
  scale_y_continuous(breaks = seq(0,40,5)) +
  labs(title = "Gráfico xx - Consumo de produções audiovisuais versus Tipo de turista") +
  theme(plot.title=element_text(hjust = 0.5, size=11, face = "bold")) + 
  theme(axis.title.y = element_blank()) + 
  theme(axis.title.x = element_blank()) +
  theme(axis.text.x = element_text(angle = -20, vjust = 0.5, hjust=0.5)) +
  theme(legend.title = element_text(size = 10))
 
```
Produções audiovisuais: Filmes, séries, telenovelas, clipes musicais e outros